---
language: ruby
env:
  - JEKYLL_ENV=production
before_install:
  - sudo apt-get install python-pip -y
  - sudo pip install docutils pygments
before_script:
   - git clone https://github.com/gryf/jekyll-rst _plugins/jekyll-rst
install:
  - bundle install
script: bundle exec jekyll build
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  local_dir: _site
  target_branch: master
  on:
    branch: source


